# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalcuatorAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SVProgressHUD'
  
  pod 'IQKeyboardManagerSwift', '~> 6.5'
  pod "CurrencyRequest"
  pod 'Alamofire'
  pod 'Kingfisher'
  # Pods for CalcuatorAPP
  
  target 'CalcuatorAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'CalcuatorAPPUITests' do
    # Pods for testing
  end
  
end
